#project name
name: frontend

on:
  push:
    branches: [front]
  pull_request:
    branches: [front]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: webpack
        run : npm install --save-dev webpack
      - name: install sass
        run : npm install --save-dev  --unsafe-perm node-sass
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: xdaly
          password: Daliza@6642633
      - name: check branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: xdaly/images:front_eadmin
          build-args: |
            BRANCH=${{ env.BRANCH }}
          push: true
